#!/bin/bash
#
# Haskell
set -e

# if there is no explicit "module Main" declaration
# we add one that exports everything
echo -n '' > Main.hs
grep -q "module Main" "$1" || echo "module Main where" >> Main.hs
cat $1 >> Main.hs

ghc -outputdir . $GHCFLAGS -main-is AltMain Main.hs "$3" -o "$2"
