#!/bin/bash
#
# Lua
#
# Library compilation of Lua programs for Udge.
#
#
# Copyright (C) 2020-2022  Rudy Matela
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
set -e

cat "$1" "$3" >lib-and-main.lua
luac -o "$2" lib-and-main.lua
rm lib-and-main.lua

# This script used to be simply:
#
#     luac -o "$2" "$1" "$3"
#
# Unfortunately, starting with lua5.4, this no longer works, see:
#
#     $ cp .../udge/examples/add/add.lua .
#     $ cp .../udge/problem/add/6/main.lua .
#     $ luac -o add add.lua main.lua
#     free(): double free detected in tcache 2
#     Aborted (core dumped)
#
# Things work fine with older versions of lua:
#
#     $ luac5.1 -o add add.lua main.lua
#     $ luac5.2 -o add add.lua main.lua
#     $ luac5.3 -o add add.lua main.lua
#
# With 5.4 things break:
#
#     $ luac5.4 -o add add.lua main.lua
#     free(): double free detected in tcache 2
#     Aborted (core dumped)
