#!/bin/bash
#
# check: check the output folder of a solution
#
# This file is part of Udge.
#
#
# Copyright (C) 2015-2020  Rudy Matela
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
# usage:
#   check path/to/problem path/to/out
prefix="$(dirname "$(dirname "$(dirname "$0")")")"
. "$prefix/lib/udge/core"

fail() {
	echo "$@"
	exit 1
}

set="$1"
out="$2"
verbose="$3"

[ -n "$set" ] || errxit "must provide input folder"
[ -n "$out" ] || errxit "must provide output folder"

[ -d "$set" ] || errxit "input folder not found"
[ -d "$out" ] || errxit "output folder not found"

total=0
outof=`n-points-path "$set"`
for idir in $set/*/
do
	[ -d $idir ] || idir=$set/
	id=`echo $idir | sed -e "s|$set/||"`
	odir=$out/$id
	pts=`cator1 $idir/pts`
	[ -n "$verbose" ] && echo "Conferring $odir against $idir"
	$lib/check-1 $idir $odir && ((total+=$pts)) || break
done
echo $total/$outof
