#!/bin/bash
#
# Some core utilities.
# To be imported from other Udge scripts.

. /etc/udge/conf

errxit() {
	echo "`basename "$0"`, error: $@" >/dev/stderr
	exit 1
}

cator1() {
	[ -f "$1" ] && cat $1 || echo 1
}

ls-users() {
	[ -d $USERS ] || errxit "could not find USERS=$USERS"
	find $USERS/ -mindepth 1 -maxdepth 1 -type d | sed -e "s,.*/,," | sort
}

ls-problems() {
	[ -d $PROBLEMS ] || errxit "could not find PROBLEMS=$PROBLEMS"
	find $PROBLEMS/ -mindepth 1 -maxdepth 1 -type d | sed -e "s,.*/,," | sort
}

[ -d "$prefix" ] || errxit "prefix directory ($prefix) does not exist, broken Udge installation?"
bin=$prefix/bin
lib=$prefix/lib/udge
