#!/bin/bash
#
# Some core utilities.
# To be imported from other Udge scripts.

. /etc/udge/conf

errxit() {
	echo "`basename "$0"`, error: $@" >/dev/stderr
	exit 1
}

cator1() {
	[ -f "$1" ] && cat $1 || echo 1
}

ls-users() {
	[ -d $PROBLEMS_DIR ] || errxit "could not find USERS_DIR=$USERS_DIR"
	find $USERS_DIR/ -maxdepth 1 -type d | sed -e "s,.*/,," | sort
}

ls-problems() {
	[ -d $PROBLEMS_DIR ] || errxit "could not find PROBLEMS_DIR=$PROBLEMS_DIR"
	find $PROBLEMS_DIR/ -maxdepth 1 -type d | sed -e "s,.*/,," | sort
}

[ -d "$prefix" ] || errxit "prefix directory ($prefix) does not exist, broken Udge installation?"
bin=$prefix/bin
lib=$prefix/lib/udge
