#!/bin/bash
#
# lib/udge/html: HTML utilities, supposed to be sourced in other scripts
#
# This file is part of Udge.
#
#
# Copyright (C) 2020-2021  Rudy Matela
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

install-csss() {
	mkdir -p "$PUBLIC_HTML"

	dst="$PUBLIC_HTML/bootstrap.css"
	[ -e "$dst" ] || cp -v "$lib/bootstrap.css" "$dst"

	dst="$PUBLIC_HTML/udge.css"
	[ -e "$dst" ]                  || cp -v "$lib/udge.css" "$dst"
	[ "$dst" -nt "$lib/udge.css" ] || cp -v "$lib/udge.css" "$dst"
}

html-header() {
cat <<HTML
<!doctype html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
HTML
[ -n "$page_author" ] && echo "<meta name=\"author\" content=\"$page_author\">"
cat <<HTML
<link rel="stylesheet" href="/bootstrap.css">
<link rel="stylesheet" href="/udge.css">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>$@</title>
</head>
<body>
<div class="container-fluid" style="max-width: 48em">
HTML
}


html-navbar() {
if [ -n "$1" ]
then
	sed -e "s,^.*>$1<.*$,<b>&</b>,"
else
	cat
fi <<HTML
<p style="margin-top: 1em">
<a href="/">index</a>
`for item in submit rank $NAVBAR; do echo "| <a href=\"/$item\">$item</a>"; done`
</p>
HTML
}


html-footer() {
cat <<HTML
</div>
</body>
</html>
HTML
}

html-escape() {
	if [ -n "$1" ]
	then
		echo "$@"
	else
		cat
	fi | sed -e "s/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/\"/\&quot;/g; s/'/\&\#39;/g"
}
