#!/bin/bash
html-header() {
cat <<HTML
<!doctype html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<link rel="stylesheet" href="/bootstrap.min.css"/>
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>$@</title>
</head>
<body>
<div class="container-fluid">
HTML
}


html-navbar() {
if [ -n "$1" ]
then
	sed -e "s,^.*>$1<.*$,<b>&</b>,"
else
	cat
fi <<HTML
<p style="margin-top: 1em">
<a href="/">index</a>
|
<a href="/submit">submit</a>
|
<a href="/rank">rank</a>
</p>
HTML
}


html-footer() {
cat <<HTML
</div>
</body>
</html>
HTML
}
