#!/bin/bash
#
# usage: ./bin/markdown file.md > file.html
prefix="$(dirname "$(dirname "$(dirname "$0")")")"
. "$prefix/lib/udge/core"
. "$lib/html"

index=
[ "`basename $1`" = index.md ] && index=index

html-header "`head -1 "$1"`"
html-navbar $index
markdown "$@"
html-navbar $index
html-footer
