#!/bin/bash
#
# usage: lib/udge/markdown file.md > file.html
#
# This file is part of Udge.
#
#
# Copyright (C) 2020  Rudy Matela
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

prefix="$(dirname "$(dirname "$(dirname "$0")")")"
. "$prefix/lib/udge/core"
. "$lib/html"

index="`basename $1 .md`"

copyright="^Copyright .*[0-9][0-9][0-9][0-9].*$"

page_title="`head -1 "$1"`"
echo "$page_title" | grep -q "^##" &&
	page_title=`cat "$1" | grep '^# ' | head -1 | sed -e 's/^# //'`
page_author="`cat "$1" | grep Copyright | head -1 | sed -e "s/Copyright .*[0-9][0-9][0-9][0-9] //"`"

class() {
	sed -e 's/^|/\&nbsp; | \&nbsp;/' |
	sed -e 's/<table>/<table class="table table-hover">/'
}

marky() {
	sed -e 's|^{#\([a-z0-9-]*\)}$|<a name="\1"></a>|'
}

multicolumn() {
	sed -e 's,^<p>%%(%%</p>$,<div class="twocolumns"><div class="left">,' |
	sed -e 's,^<p>%%|%%</p>$,</div><div class="right">,' |
	sed -e 's,^<p>%%)%%</p>$,</div></div>,'
}

[ "$page_title" == "$NAME" ] || page_title="$page_title - $NAME"
html-header $page_title
html-navbar $index
if grep -q "$copyright" "$@"
then
	grep -B10000 "$copyright" "$@" | head -n -1 | marky | markdown | class | multicolumn
	html-navbar $index
	echo '<p style="text-align:right;font-size:smaller">'
	# This automatically links a few license types
	grep -A10000 "$copyright" "$@" |
		sed -e 's|CC BY-SA 4.0|<a href="https://creativecommons.org/licenses/by-sa/4.0/">&</a>|' |
		sed -e 's|CC BY-NC-ND 4.0|<a href="https://creativecommons.org/licenses/by-nc-nd/4.0/">&</a>|' |
		sed -e 's|GFDL 1.3|<a href="https://www.gnu.org/licenses/fdl-1.3.html">&</a>|' |
		sed -e "s/$/<br>/"
	echo '</p>'
else
	cat "$@" | marky | markdown | class | multicolumn
	html-navbar $index
fi
html-footer
