#!/bin/bash
#
# usage: lib/udge/markdown file.md > file.html
#
# This file is part of Udge.
#
#
# Copyright (C) 2020-2023  Rudy Matela
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

prefix="$(dirname "$(dirname "$(dirname "$0")")")"
. "$prefix/lib/udge/core"
. "$lib/html"

index="`basename $1 .md`"

copyright='^\(Copyright\|©\|(C)\) .*[0-9][0-9][0-9][0-9].*$'

page_title="`head -1 "$1"`"
echo "$page_title" | grep -q "^##" &&
	page_title="`cat "$1" | grep '^# ' | head -1 | sed -e 's/^# //'`"
page_title="`echo $page_title | sed -e "s/---/—/g;s/--/–/g"`"
page_author="`cat "$1" | grep Copyright | head -1 | sed -e "s/Copyright .*[0-9][0-9][0-9][0-9] //"`"

class() {
	sed -e 's|^<h\(.\)>\(.*[^ ]\)  *#\(.*\)</h.>$|<h\1 id="\3">\2</h\1>|' |
	sed -e 's/^|/\&nbsp; | \&nbsp;/' |
	sed -e 's/<table>/<table class="table table-hover">/'
}

colour-fractions() {
	# Hacky?  ¯\_(ツ)_/¯  Hey, as long as it works...
	sed -Ee '
		s,\* +1/1:,* <span class="one">1/1</span>:,;
		s,\* +2/2:,* <span class="one">2/2</span>:,;
		s,\* +3/3:,* <span class="one">3/3</span>:,;
		s,\* +4/4:,* <span class="one">4/4</span>:,;
		s,\* +5/5:,* <span class="one">5/5</span>:,;
		s,\* +6/6:,* <span class="one">6/6</span>:,;
		s,\* +8/8:,* <span class="one">8/8</span>:,;
		s,\* +9/9:,* <span class="one">9/9</span>:,;
		s,\* +10/10:,* <span class="one">10/10</span>:,;
		s,\* +12/12:,* <span class="one">12/12</span>:,;
		s,\* +16/16:,* <span class="one">16/16</span>:,;
		s,\* +18/18:,* <span class="one">18/18</span>:,;
		s,\* +20/20:,* <span class="one">20/20</span>:,;
		s,\* +24/24:,* <span class="one">24/24</span>:,;
		s,\* +25/25:,* <span class="one">25/25</span>:,;
		s,\* +30/30:,* <span class="one">30/30</span>:,;
		s,\* +32/32:,* <span class="one">32/32</span>:,;
		s,\* +40/40:,* <span class="one">40/40</span>:,;
		s,\* +50/50:,* <span class="one">50/50</span>:,;
		s,\* +60/60:,* <span class="one">60/60</span>:,;
		s,\* +64/64:,* <span class="one">64/64</span>:,;
		s,\* +100/100:,* <span class="one">100/100</span>:,;
		s,\* +120/120:,* <span class="one">120/120</span>:,;
		s,\* +128/128:,* <span class="one">128/128</span>:,;
		s,\* +256/256:,* <span class="one">256/256</span>:,;
		s,\* +360/360:,* <span class="one">360/360</span>:,;
		s,\* +(0/[0-9]+):,* <span class="zero">\1</span>:,;
		s,\* +([0-9]+/[0-9]+):,* <span class="frac">\1</span>:,;
	'
}

marky() {
	sed -e 's|^{#\([a-z0-9-]*\)}$|<a name="\1"></a>|'
}

multicolumn() {
	sed -e 's|%%nothing%%||g' |
	sed -e 's|<p>%%\([a-z]*\){%%</p>|<div class="panel panel-default \1"><div class="panel-body">|' |
	sed -e 's|<p>%%}[a-z]*%%</p>|</div></div>|' |
	sed -e 's,^<p>%%(%%</p>$,<div class="twocolumns"><div class="left">,' |
	sed -e 's,^<p>%%|%%</p>$,</div><div class="right">,' |
	sed -e 's,^<p>%%)%%</p>$,</div></div>,'
}

[ "$page_title" == "$NAME" ] || page_title="$page_title – $NAME"
html-header "$page_title"
html-navbar $index
if grep -q "$copyright" "$@"
then
	grep -B10000 "$copyright" "$@" | head -n -1 | marky | colour-fractions | markdown | class | multicolumn
	html-navbar $index
	echo '<p style="text-align:right;font-size:smaller">'
	# This automatically links a few license types
	grep -A10000 "$copyright" "$@" |
		sed -e 's|\[\(.*\)\](\(.*\))|<a href="\2">\1</a>|' |
		sed -e 's|CC BY-SA 4.0|<a href="https://creativecommons.org/licenses/by-sa/4.0/">&</a>|' |
		sed -e 's|CC BY-NC-ND 4.0|<a href="https://creativecommons.org/licenses/by-nc-nd/4.0/">&</a>|' |
		sed -e 's|GFDL 1.3|<a href="https://www.gnu.org/licenses/fdl-1.3.html">&</a>|' |
		sed -e "s/$/<br>/"
	echo '</p>'
else
	cat "$@" | marky | markdown | class | multicolumn
	html-navbar $index
fi
html-footer
