#!/bin/bash
#
# usage: lib/udge/rank-html
#
# This file is part of Udge.
#
#
# Copyright (C) 2020  Rudy Matela
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

prefix="$(dirname "$(dirname "$(dirname "$0")")")"
. "$prefix/lib/udge/core"
. "$lib/html"

mkrow() {
	c='\([^ ]*\) *'
	sed -e "s|^ *$c$c\(.*\)$|<pos<\1>><user<\2>><score<\3>>|" |
	sed -e "s|  *|>><score<|g" |
	sed -e "s|<pos<\([^>]*\)>>|<td style=\"text-align: right\">\1</td>|g" |
	sed -e "s|<user<\([^>]*\)>>|<td><a href=\"/u/\1\">\1</a></td>|g" |
	sed -e "s|<score<\([^>]*\)>>|<td style=\"text-align: right\">\1</td>|g" |
	sed -e "s|^|<tr>|" |
	sed -e "s|$|</tr>|"
}

html-header "User Rank – $NAME"
html-navbar rank
echo "<h2>User Rank – $NAME</h2>"
echo '<table class="table table-hover">'
echo '<thead>'
echo "# user `$lib/score/$SCORE`" | html-escape | mkrow | sed -e 's/<td/<th/;s/td>/th>/' | sed -e "s|<a[^>]*>||;s|</a>||"
echo '</thead>'
echo '<tbody>'
$bin/udge-rank | mkrow
echo '</tbody>'
echo '</table>'
html-navbar rank
html-footer
