#!/bin/bash
#
# usage: lib/udge/rank-html
#
# This file is part of Udge.
#
#
# Copyright (C) 2020-2023  Rudy Matela
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

prefix="$(dirname "$(dirname "$(dirname "$0")")")"
. "$prefix/lib/udge/core"
. "$lib/html"
$SHARING_OPTIONS && . "$lib/cgi"

denon="$1"
anonymize="s|<user<-[^>]*>>|<td>anonymous</td>|"
[ -n "$denon" ] && anonymize="s|<user<-\([^/]*\)/\([^>]*\)>>|<td><a href=\"/u/\2\">\1</a></td>|g"

mkrow() {
	c='\([^ ]*\) *'
	sed -e "s|^ *$c$c\(.*\)$|<pos<\1>><user<\2>><score<\3>>|" |
	sed -e "s|  *|>><score<|g" |
	sed -e "s|<pos<\([^>]*\)>>|<td style=\"text-align: right\">\1</td>|g" |
	sed -e "$anonymize" |
	sed -e "s|<user<\([^>]*\)>>|<td><a href=\"/u/\1\">\1</a></td>|g" |
	sed -e "s|<score<\([^>]*\)>>|<td style=\"text-align: right\">\1</td>|g" |
	sed -e "s|^|<tr>|" |
	sed -e "s|$|</tr>|"
}

html-header "$RANKNAME – $NAME"
html-navbar "$RANKPATH"
echo "<h2>$RANKNAME – $NAME</h2>"
echo '<table class="table table-hover">'
echo '<thead>'
echo "# user `$lib/score/$SCORE`" | html-escape | mkrow | sed -e 's/<td/<th/;s/td>/th>/' | sed -e "s|<a[^>]*>||;s|</a>||"
echo '</thead>'
if any-users  # makes it so that the HTML is tidy with no users
then
	echo '<tbody>'
	$bin/udge-rank anon "$denon" | mkrow
	echo '</tbody>'
fi
echo '</table>'
$SHARING_OPTIONS && find-user-form
html-navbar "$RANKPATH"
html-footer
