#!/bin/bash
#
# lib/udge/timeavg: scales and computes the time and memory average
#
# usage: timeavg /run/udge/<SLOT>/check/run
#
#
# Copyright (C) 2020-2021  Rudy Matela
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
# If this program cannot parse input, it prints "- -"
# including when the run folder does not exist.
prefix="$(dirname "$(dirname "$(dirname "$0")")")"
. "$prefix/lib/udge/core"

exitwith() {
	echo "$@"
}

run="$1"
[ -n "$run" ] || errxit "must provide run folder"

# avg computes the average of numbers given in standard input.
# arguments:
# 1. the format string
# 2. an optional scaling factor
avg() {
	grep -E '^[0-9]+(|\.[0-9]*)$' |
	awk "{t+=\$1}END{printf \"$1\",(NR?t/NR$2:\"-1\")}" |
	sed -e "s/-[^ ]*/-/g"
}

head -1q $run/{,*/}time 2>/dev/null
echo ------
head -1q $run/{,*/}time 2>/dev/null | cut -d\  -f1 | avg "%.0f "  "*1000"
head -1q $run/{,*/}time 2>/dev/null | cut -d\  -f2 | avg "%.0f\n" "/1024"
