#!/bin/bash
#
# usage: ./bin/user-html <user>
prefix="$(dirname "$(dirname "$(dirname "$0")")")"
. "$prefix/lib/udge/core"
. "$lib/html"
errxit() {
	echo "$0, error: $@" >/dev/stderr
	echo "usage:" >/dev/stderr
	echo "  $0 <user>" >/dev/stderr
	exit 1
}
user="$1"
[ -n "$user" ] || errxit "missing <user> argument"
[ -d "$USERS_DIR/$user" ] || errxit "user not found"
dirname="`dirname $0`"

html-header "$user - Udge"
echo "<h2>$user - Udge</h2>"

echo "<h3>Stats</h3>"
$bin/udge-user-stats $user overall | sed -e "s,^,<p>,;s,$,</p>,"

echo "<h3>Problems & Tries</h3>"
echo '<table class="table">'
echo '<thead>'
echo '<tr><th>problem</th><th>score</th><th>tries</th></tr>'
echo '</thead>'
echo '<tbody>'
$bin/udge-user-stats $user problem | sed -e 's,\([^ ]*\)  *\([^ ]*\)  *\([^ *]\),<tr><td><a href="/\1">\1</a></td><td>\2</td><td>\3</td></tr>,'
echo '</tbody>'
echo '</table>'

echo "<h3>Latest submissions</h3>"
echo '<table class="table">'
echo '<thead>'
echo '<tr><th>timestamp (UTC)</th><th>problem</th><th>language</th><th>score</th><th>reason</th></tr>'
echo '</thead>'
echo '<tbody>'
$bin/udge-latest-results "$user" | sed -e 's,\([^ ]* [^ ]*\)  \([^ ]*\)\.\([^ ]*\)  [ ]*\([^ ]*\)[ ]*\(.*\),<tr><td>\1</td><td><a href="/\2">\2</a></td><td>\3</td><td>\4</td><td>\5</td></tr>,'
echo '</tbody>'
echo '</table>'

html-footer
