#!/bin/bash
#
# usage: lib/udge/user-html <user>
#
# This file is part of Udge.
#
#
# Copyright (C) 2020  Rudy Matela
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

prefix="$(dirname "$(dirname "$(dirname "$0")")")"
. "$prefix/lib/udge/core"
. "$lib/html"
errxit() {
	echo "$0, error: $@" >&2
	echo "usage:"        >&2
	echo "  $0 <user>"   >&2
	exit 1
}
user="$1"
[ -n "$user" ] || errxit "missing <user> argument"
[ -d "$USERS/$user" ] || errxit "user not found"
dirname="`dirname $0`"

name="`cat $USERS/$user/name 2>/dev/null || echo $user`"

html-header "$user @ $NAME"
html-navbar
echo "<h2>$name @ $NAME</h2>"

$bin/udge-user-stats $user overall | sed -e 's,^,<p>,;s,$,</p>,;s,the rank,<a href="/rank">the rank</a>,'

colour-fractions() {
	# Hacky?  ¯\_(ツ)_/¯  Hey, as long as it works...
	sed -Ee '
		s,[0-9]+/[0-9]+,#&#,;
		s,#1/1#,<span class="one">1/1</span>,;
		s,#2/2#,<span class="one">2/2</span>,;
		s,#3/3#,<span class="one">3/3</span>,;
		s,#4/4#,<span class="one">4/4</span>,;
		s,#5/5#,<span class="one">5/5</span>,;
		s,#6/6#,<span class="one">6/6</span>,;
		s,#8/8#,<span class="one">8/8</span>,;
		s,#10/10#,<span class="one">10/10</span>,;
		s,#12/12#,<span class="one">12/12</span>,;
		s,#30/30#,<span class="one">30/30</span>,;
		s,#60/60#,<span class="one">60/60</span>,;
		s,#360/360#,<span class="one">360/360</span>,;
		s,#(0/[0-9]+)#,<span class="zero">\1</span>,;
		s,#([0-9]+/[0-9]+)#,<span class="frac">\1</span>,;
	'
}

tmp=`mktemp "/tmp/udge-latest-results.XXXXXXXXXX"`
$bin/udge-latest-results "$user" > "$tmp"
if [ -s "$tmp" ]
then
	echo "<h3>Latest submissions</h3>"
	echo '<table class="table table-hover">'
	echo '<thead>'
	echo '<tr><th>timestamp (UTC)</th><th>problem</th><th>language</th><th>score</th><th>runtime</th><th>reason</th></tr>'
	echo '</thead>'
	echo '<tbody>'
	cat "$tmp" |
		sed -Ee 's,^([^ ]+) ([^ ]+)  ([^ ]+)\.([^ ]+)  [ ]*([^ ]+)[ ]*([^ ]+)[ ]*([^ ]+)(.*)$,<tr><td>\1\&nbsp;\2</td><td><a href="/\3">\3</a></td><td>\4</td><td>\5</td><td>\6 \7</td><td>\8</td></tr>,' |
		colour-fractions
	echo '</tbody>'
	echo '</table>'
else
	echo '<p>No submissions yet.</p>'
fi
rm "$tmp"

echo "<h3>Scores by problem</h3>"
echo '<table class="table table-hover">'
echo '<thead>'
echo "<tr><th>problem</th><th>best score</th><th>tries</th><th>languages</th></tr>"
echo '</thead>'
echo '<tbody>'
$bin/udge-user-stats $user problem |
	sed -Ee 's,^  ([^ ]+) +([^ ]+) +([^ ]+) *(.*)$,<tr><td>\&nbsp; \&nbsp; <a href="/\1">\1</a></td><td>\2</td><td>\3</td><td>\4</td></tr>,' |
	sed -Ee 's,^[^<].*$,<tr style="background-color: #f8f8f8"><td>&</td><td></td><td></td><td></td></tr>,' |
	colour-fractions
echo '</tbody>'
echo '</table>'

html-navbar
html-footer
