#!/bin/bash
#
# usage: ./bin/user-html <user>
#
# This file is part of Udge.
#
#
# Copyright (C) 2020  Rudy Matela
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

prefix="$(dirname "$(dirname "$(dirname "$0")")")"
. "$prefix/lib/udge/core"
. "$lib/html"
errxit() {
	echo "$0, error: $@" >&2
	echo "usage:"        >&2
	echo "  $0 <user>"   >&2
	exit 1
}
user="$1"
[ -n "$user" ] || errxit "missing <user> argument"
[ -d "$USERS/$user" ] || errxit "user not found"
dirname="`dirname $0`"

html-header "$user - Udge"
html-navbar
echo "<h2>$user - Udge</h2>"

echo "<h3>Stats</h3>"
$bin/udge-user-stats $user overall | sed -e 's,^,<p>,;s,$,</p>,;s,the rank,<a href="/rank">the rank</a>,'

echo "<h3>Problems & Tries</h3>"
echo '<table class="table table-hover">'
echo '<thead>'
echo '<tr><th>problem</th><th>score</th><th>tries</th></tr>'
echo '</thead>'
echo '<tbody>'
$bin/udge-user-stats $user problem | sed -Ee 's,^([^ ]+) +([^ ]+) +([^ ]+)$,<tr><td><a href="/\1">\1</a></td><td>\2</td><td>\3</td></tr>,'
echo '</tbody>'
echo '</table>'

tmp=`mktemp "/tmp/udge-latest-results.XXXXXXXXXX"`
$bin/udge-latest-results "$user" > "$tmp"
if [ -s "$tmp" ]
then
	echo "<h3>Latest submissions</h3>"
	echo '<table class="table table-hover">'
	echo '<thead>'
	echo '<tr><th>timestamp (UTC)</th><th>problem</th><th>language</th><th>score</th><th>reason</th></tr>'
	echo '</thead>'
	echo '<tbody>'
	cat "$tmp" | sed -Ee 's,^([^ ]+ [^ ]+)  ([^ ]+)\.([^ ]+)  [ ]*([^ ]+)[ ]*(.*)$,<tr><td>\1</td><td><a href="/\2">\2</a></td><td>\3</td><td>\4</td><td>\5</td></tr>,'
	echo '</tbody>'
	echo '</table>'
else
	echo '<p>No submissions yet.</p>'
fi
rm "$tmp"

html-navbar
html-footer
