#!/bin/bash
#
# Custom compilation script for the "salaries" problem.
#
#
# Copyright (C) 2023  Rudy Matela
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
errxit() {
	echo "$@" >&2
	exit 1
}

set -e
dirname=`dirname $0`
case "$1" in
	*.zip)  unzip   "$1" employee.h employee.c main.c ;;
	*.tar*) tar -xf "$1" employee.h employee.c main.c ;;
	*) errxit "aborted: only zip and tar submissions are supported for this problem" ;;
esac

diff -q --ignore-matching-lines='^//' -iEZbwB "$dirname/employee.h" employee.h ||
errxit "aborted: the header file has been tampered with"

cc $CFLAGS employee.c main.c -o "$2" -lm
