#!/bin/bash
#
# checks reference output against stdout and the log file pointed by args
#
# This file is part of Udge
#
#
# Copyright (C) 2020-2021  Rudy Matela
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
# usage:
#   check-out reference/out run/out [verbose]

set -e
diff -q "$1" "$2" 2>/dev/null
sol=`dirname "$1"`
run=`dirname "$2"`
[ -n "$sol" ]
[ -n "$run" ]
log=`cat $sol/args`
diff -rud "$1" "$run/files/$log" 2>/dev/null
