#!/bin/bash
#
# Tarball
#
# Plain compilation of modular C programs submitted in a tarball file on Udge.
#
#
# Copyright (C) 2020-2023  Rudy Matela
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
# WARNING:
# This is disabled by default due to potential security issues.
# One can create a malicious tarball file that expands to fill the disk
# upon extraction.  Use with care!
set -e
tar -xf "$1" --wildcards '*.c' '*.h'  # just C and header files
cc $CFLAGS *.c -o "$2" -lm
