#!/bin/bash
#
# Configuration file for Udge
#
# Udge - GPLv2 - Copyright (C) 2020 Rudy Matela

NAME="Udge Online Judge"

USERS=/var/lib/udge/users
PROBLEMS=/var/lib/udge/problem
SUBMISSIONS=/var/lib/udge/submissions
RESULTS=/var/lib/udge/results
PUBLIC_HTML=/var/lib/udge/html
RUN=/var/lib/udge/run

SCORE=fractions
NEW_USER=true

GHCFLAGS=-dynamic # for Arch Linux

RUN_WITH="
udge-run-1@localhost
udge-run-2@localhost
udge-run-3@localhost
udge-run-4@localhost
udge-run-5@localhost
udge-run-6@localhost
"
