#!/bin/bash
#
# Configuration file for Udge
#
# Udge - GPLv2 - Copyright (C) 2020-2021  Rudy Matela

NAME="Udge Online Judge"

USERS=/var/lib/udge/users
PROBLEMS=/var/lib/udge/problem
SUBMISSIONS=/var/lib/udge/submissions
RESULTS=/var/lib/udge/results
SLOTS=/var/lib/udge/slot
PUBLIC_HTML=/var/lib/udge/html
BACKUPS=/var/lib/udge/backups
RUN=/run/udge

SCORE=fractions
NEW_USER=true
INVALID_USER_REGEX="(^admin|admin$|[^a-z]admin|admin[^a-z])"

JAVA_EXTRA_TIME=2
CS_EXTRA_TIME=2
ERL_EXTRA_TIME=6
RKT_EXTRA_TIME=2

GHCFLAGS=-dynamic # for Arch Linux
GUILE_AUTO_COMPILE=0 # avoid Guile's funny business of using ~/.cache
MAX_PROCESSES=1024
