#!/bin/bash
#
# Configuration file for Udge
#
# Udge - GPLv2 - Copyright (C) 2020-2021  Rudy Matela

NAME="Udge Online Judge"

USERS=/var/lib/udge/users
PROBLEMS=/var/lib/udge/problem
SUBMISSIONS=/var/lib/udge/submissions
RESULTS=/var/lib/udge/results
SLOTS=/var/lib/udge/slot
PUBLIC_HTML=/var/lib/udge/html
BACKUPS=/var/lib/udge/backups
RUN=/run/udge

SCORE=fractions
NEW_USER=true

GHCFLAGS=-dynamic # for Arch Linux
MAX_PROCESSES=512
