#!/bin/bash
#
# Custom compilation script for the "salaries" problem.
#
# This file is part of Udge.
#
# This compilation script expects a C program in a zip/tar archive.
# Check the accompanying desc.md for more details of what is expected.
#
#
# Copyright (C) 2023  Rudy Matela
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
errxit() {
	echo "$@" >&2
	exit 1
}

set -e

# The name of the library we are unpacking from the zip/tar archive.
lib=employee

tarw="tar --strip-components=1 --wildcards"

# Unpack the zip / tar archive into src/
mkdir -p src
mime="`file -b --mime-type "$1"`"
case $mime in
application/zip)
	unzip -qjn "$1" -dsrc   "$lib.h"   "$lib.c"   "main.c" ||
	unzip -qjn "$1" -dsrc "*/$lib.h" "*/$lib.c" "*/main.c" ;;
application/gzip|application/x-tar)
	tar    -xf "$1" -Csrc   "$lib.h"   "$lib.c"   "main.c" ||
	$tarw  -xf "$1" -Csrc "*/$lib.h" "*/$lib.c" "*/main.c" ;;
*)
	errxit "aborted: only zip and tar submissions are supported for this problem, got $mime" ;;
esac

# Checks if the header file has been tampered with
dirname="`dirname $0`"
diff -q --ignore-matching-lines='^//' -iEZbwB "$dirname/$lib.h" "src/$lib.h" ||
errxit "aborted: the header file has been tampered with"

# Compiles the program
[ -f "$3" ] && cp "$3" src # copy the main.c if it exists
cd src
cc $CFLAGS $lib.c main.c -o "../$2" -lm
cd ..
rm -r src
