#!/bin/bash
# Configuration file for the judge
SALT_FILE=/etc/udge/salt
USERS_DIR=/etc/udge/users
PROBLEMS_DIR=/etc/udge/problem
UNJUDGED_DIR=/tmp/submissions
RESULTS_DIR=/tmp/results
GHCFLAGS=-dynamic # for Arch Linux
