#!/bin/bash
#
# examples/create-new-user: creates an Udge user through HTTP
#
# This file is part of Udge.
#
#
# Copyright (C) 2020  Rudy Matela
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

curl \
	-w"%{http_code}\n" \
	-sXPOST udge/new-user \
	-duser="$1" \
	-demail="$2" \
	-demail-confirmation="$2" \
	-dpassword="$3" \
	-dpassword-confirmation="$3" \
	-dname="$4" \
	| grep -E "(<h.>|help-block|^[0-9]+$)" \
	| sed -e "s/<[^>]*>//g"
