#!/bin/bash
#
# The default scoring for Udge, distribution over fractions.
#
# This file is part of Udge.
#
#
# Copyright (C) 2020-2022  Rudy Matela
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
# To use this, simply put the following on /etc/udgerc:
#
# SCORE=fractions
#
# Without arguments, this prints the title of each data point:
#
# $ lib/udge/score/fractions
# =1 ≥⅔ ≥½ ≥⅓ >0
#
# With an username, this prints the score for that user:
# $ lib/udge/score/fractions john-doe
# 9 12 17 17 18
#
# The above means:
# * 9 fully-solved problems
# * 12 problems with a ≥⅔ score
# * 17 problems with a ≥½ score
# * 17 problems with a ≥⅓ score
# * 18 problems with a >0 score
#
#
# By creating a program following the same interface:
#
# * titles with no argument
# * data points with user argument
#
# it is possible to use Udge with a custom scoring.
prefix="$(dirname "$(dirname "$(dirname "$(dirname "$0")")")")"
. "$prefix/lib/udge/core"
user="$1"
[ -n "$user" ] || finish- "=1 ≥⅔ ≥½ ≥⅓ >0"
[ -d "$USERS/$user" ] || errxit "user not found"

bests() {
	cat $RESULTS/$user/*/best 2>/dev/null
}

problems-tried() {
	bests | wc -l
}

problems-solved() {
	bests | bc | grep "^1$" | wc -l
}


problems-scored() {
	bests | grep -v "^0/" | wc -l
}


problems-() {
	bests | sed -e "s/^/$1 <= $2*/" | bc | grep "^1$" | wc -l
}

echo "`problems-solved` `problems- 2 3` `problems- 1 2` `problems- 1 3` `problems-scored`"
