#!/bin/bash
prefix="$(dirname "$(dirname "$(dirname "$(dirname "$0")")")")"
. "$prefix/lib/udge/core"
user="$1"
[ -n "$user" ] || finish- "#-solved"
[ -d "$USERS/$user" ] || errxit "user not found"

bests() {
	cat $RESULTS/$user/*/best 2>/dev/null
}

bests | bc | grep "^1$" | wc -l
