#!/bin/bash
#
# Simple scoring for Udge with the sum of points
#
# This file is part of Udge.
#
#
# Copyright (C) 2020-2021  Rudy Matela
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
prefix="$(dirname "$(dirname "$(dirname "$(dirname "$0")")")")"
. "$prefix/lib/udge/core"
user="$1"
[ -n "$user" ] || finish- "#-solved"
[ -d "$USERS/$user" ] || errxit "user not found"

bests() {
	cat $RESULTS/$user/*/best 2>/dev/null
}

# like bests but in a single line
bests1() {
	bests | tr '\n' ' '
}

bests1 |
	sed -e 's/ / + /g; s/$/0\n/; s/^/scale=1\n/' |
	bc |
	sed -e 's/^\./0./'
