# Builds and tests Udge on GitHub Actions
#
# 2023  Rudy Matela

name: build
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: tecolicom/actions-use-apt-tools@v1 # MIT license
        with:
          tools: clitest fcgiwrap discount libmarkdown2 cracklib-runtime libcrack2 tidy

      - run: sudo update-cracklib

      - run: echo $0
      - run: echo $SHELL
      - run: whoami
      - run: make --version
      - run: diff --version
      - run: sed --version
      - run: gcc --version
      - run: python --version
      - run: ghc --version
      - run: clitest --version
      - run: nginx -v
      - run: fcgiwrap -h
      - run: markdown --version
      - run: tidy --version
      - run: echo 'print --version' | cracklib-check

      - run: cat /etc/hosts
      - run: sudo sed -i 's/localhost$/localhost udge udge.example.com/' /etc/hosts
      - run: cat /etc/hosts

      - name: Check out repository
        uses: actions/checkout@v3

      - run: sudo make install
      - run: sudo -u udge udge-update-all-problem-htmls
      - run: sudo -u udge udge-update-all-user-htmls
      - run: sudo -u udge udge-update-rank-html

      - run: sudo ln -rsf /etc/nginx/sites-available/udge /etc/nginx/sites-enabled/udge
      - run: sudo make start-services
      - run: sudo make enable-nginx-udge-site

      - run: make test-makefile
      - run: make judge.clitest hello.clitest add.clitest runtime.clitest

      - run: make sandbox.clitest
      - run: make sandbox-fork.clitest

      # - run: make test-web
      - run: make index.clitest test-no-broken-links tidy

      - run: make SUDO_UDGE="sudo -u udge" new-user.clitest find-user.clitest names.clitest

      - run: make SUDO_UDGE="sudo -u udge" test-happy
