# Builds and tests Udge on GitHub Actions
#
# 2023  Rudy Matela

name: build
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: tecolicom/actions-use-apt-tools@v1 # MIT license
        with:
          tools: clitest fcgiwrap discount

      - run: echo $0
      - run: echo $SHELL
      - run: make --version
      - run: diff --version
      - run: sed --version
      - run: gcc --version
      - run: python --version
      - run: ghc --version
      - run: clitest --version
      - run: nginx -v
      - run: fcgiwrap -h
      - run: cat /etc/hosts

      - name: Check out repository
        uses: actions/checkout@v3

      - run: make dev-setup
      - run: sudo make dev-install
      - run: sudo sed -ie 's/localhost$/localhost udge udge.example.com/' /etc/hosts

      - run: make test-makefile
      #- run: make judge.clitest hello.clitest add.clitest runtime.clitest

      - run: make html
      - run: sudo make start-services
      - run: sudo make enable-nginx-udge-site
      - run: curl -s udge
      - run: tail /var/log/nginx/access.log
      - run: cat /etc/nginx/nginx.conf

      - run: make sandbox.clitest
